version: "3.7"
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - overlay

  kalah:
    container_name: kalah
    build: ./
    image: backbase/kalah:latest
    depends_on:
      - redis
    ports:
      - 8080:8080
    networks:
      - overlay

networks:
  overlay: